
metadata:
  name: "Comprehensive Project Risk Analysis"
  description: "Complete risk analysis including direct costs, quality impacts, schedule effects, market variations, and risk adjustments"
  samples: 9
  sampling_method: "latin_hypercube"

variables:
  # Direct Material and Equipment
  Steel_Cost:
    type: "norm"
    parameters:
      loc: 800000
      scale: 1200000

  Maintenance_Cost:
    type: "uniform"
    parameters:
      loc: 0
      scale: 1
      
  Height:
    type: "norm"
    parameters:
      loc: 180
      scale: 10
      
  Children:
    type: "EmpiricalDistribution"
    parameters:
      data: [1, 3, 2, 4, 5, 2, 3, 4]
      method: "closest_observation"
  
      
      
correlations:
  - 0.2: [Steel_Cost, Maintenance_Cost]
  - 0.5: [Height, Maintenance_Cost]