name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.2.3, etc

jobs:
  pypi-publish:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release  # Matches the PyPI environment
      url: https://pypi.org/p/probabilit
    permissions:
      id-token: write  # For trusted publishing
    steps:
    
    - name: Checkout
      uses: actions/checkout@v5
      
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
    
    - name: Install build dependencies
      run: |
        pip install build
    
    - name: Build package
      run: |
        python -m build
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.13
