name: Python package

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        # https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies
        cache: 'pip' # caching pip dependencies # 
        cache-dependency-path: |
          pyproject.toml
          
    - name: Install package
      run: |
        pip install '.[dev]'

    - name: Run ruff format
      run: |
        ruff format . --check
        
    - name: Run ruff
      run: |
        ruff check .
        
    - name: Run pytest
      run: |
        pytest . --doctest-modules -v

    - name: Run doctests in README
      run: |
        python -m doctest README.md -o ELLIPSIS
