name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        # https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies
        cache: 'pip' # caching pip dependencies # 
        cache-dependency-path: |
          pyproject.toml
          
    - name: Install package
      run: |
        pip install '.[dev]'

    - name: Run ruff format
      run: |
        ruff format . --check
        
    - name: Run ruff
      run: |
        ruff check .
        
    - name: Run pytest
      run: |
        pytest . --doctest-modules -v