name: Type Check

on:
  push:
    branches: [ main, develop, typing ]
  pull_request:
    branches: [ main, develop, typing ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,types]"
    
    - name: Run mypy
      run: |
        mypy src/